### ISSUE TITLE
Channel function returning channel function

### ISSUE THREAD

**Issue by penguin-boxx** [winter-yuki/LambdaRPC.kt#26]
Lib:
```kotlin
suspend fun normMap(xs: List<Point>, transformNorm: suspend (Norm) -> Norm): List<Double> =
    xs.map { point -> transformNorm { it.x * it.x + it.y * it.y }(point) }
```
Client:
```kotlin
normMap(ps) { norm -> { point -> sqrt(norm(point)) } }
```
If `ps` points list contains only one point, everything is fine. If `ps` has more than one element, there is an exception on service
```
Exception in thread "DefaultDispatcher-worker-1" java.util.NoSuchElementException: Key 7bdf8f30-870a-4af0-a8a4-1cd5b99eaf94 is missing in the map.
        at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
        at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:346)
        at io.lambdarpc.service.LibService.processResponse(LibService.kt:107)
        at io.lambdarpc.service.LibService.access$processResponse(LibService.kt:18)
        at io.lambdarpc.service.LibService$execute$1$invokeSuspend$lambda-1$$inlined$collect$1.emit(Collect.kt:142)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:77)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:59)
        at io.grpc.kotlin.ServerCalls$serverCallListener$requests$1.invokeSuspend(ServerCalls.kt:227)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
If working execution channel cleanup is disabled, `map` duplicates first block result for each input list element.

**Comment by penguin-boxx** [comment]
Maybe it will be fixed on #14 done
